### ISSUE TITLE
Kapot on windows

### ISSUE THREAD

**Issue by marco12en3** [urbanjourney/urban-journey#2]
# ...

FAIL: test_cached (urban_journey.common.cached.test_cached.TestCachedProperties)
## Since bar is a cached property it will only be executed once per instance and always return 42. Only

Traceback (most recent call last):
  File "C:\users\Marco\Documents\aaron\urban-journey-master\urban_journey\common\cached\test_cached.py", line 36, in tes
t_cached
    self.assertGreater(clock()-t_0, dt)
AssertionError: 0.000206505540342479 not greater than 0.001
# 

FAIL: test_cached_class (urban_journey.common.cached.test_cached.TestCachedProperties)
## Same as the other test, but returns 37 on all instances of the class. According to [1], 37 is objectively the

Traceback (most recent call last):
  File "C:\users\Marco\Documents\aaron\urban-journey-master\urban_journey\common\cached\test_cached.py", line 63, in tes
t_cached_class
    self.assertGreater(clock() - t_0, dt)
AssertionError: 0.000733238359943673 not greater than 0.001
# 
## FAIL: test_clock (urban_journey.pubsub.test.test_clock.TestClock)

Traceback (most recent call last):
  File "C:\users\Marco\Documents\aaron\urban-journey-master\urban_journey\pubsub\test\test_clock.py", line 28, in test_c
lock
    self.assertGreaterEqual(time() - t0, 0.05)
AssertionError: 0.03051924705505371 not greater than or equal to 0.05

---

Ran 60 tests in 2.557s

FAILED (failures=3)

**Comment by marco12en3** [comment]
dont install but use develop
